# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SocialDistanceCheck.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 350))
        MainWindow.setMaximumSize(QtCore.QSize(600, 350))
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 350))
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 350))
        self.centralwidget.setBaseSize(QtCore.QSize(600, 350))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setHorizontalSpacing(35)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.time_to_wait_to_start_combo_box = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_to_wait_to_start_combo_box.sizePolicy().hasHeightForWidth())
        self.time_to_wait_to_start_combo_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_to_wait_to_start_combo_box.setFont(font)
        self.time_to_wait_to_start_combo_box.setObjectName("time_to_wait_to_start_combo_box")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.time_to_wait_to_start_combo_box.addItem("")
        self.gridLayout.addWidget(self.time_to_wait_to_start_combo_box, 2, 1, 1, 1)
        self.minimum_distance_combo_box = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimum_distance_combo_box.sizePolicy().hasHeightForWidth())
        self.minimum_distance_combo_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minimum_distance_combo_box.setFont(font)
        self.minimum_distance_combo_box.setStatusTip("")
        self.minimum_distance_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.minimum_distance_combo_box.setAutoFillBackground(False)
        self.minimum_distance_combo_box.setEditable(False)
        self.minimum_distance_combo_box.setInsertPolicy(QtWidgets.QComboBox.InsertBeforeCurrent)
        self.minimum_distance_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.minimum_distance_combo_box.setMinimumContentsLength(0)
        self.minimum_distance_combo_box.setIconSize(QtCore.QSize(16, 16))
        self.minimum_distance_combo_box.setFrame(True)
        self.minimum_distance_combo_box.setObjectName("minimum_distance_combo_box")
        self.minimum_distance_combo_box.addItem("")
        self.minimum_distance_combo_box.addItem("")
        self.minimum_distance_combo_box.addItem("")
        self.minimum_distance_combo_box.addItem("")
        self.minimum_distance_combo_box.addItem("")
        self.minimum_distance_combo_box.addItem("")
        self.gridLayout.addWidget(self.minimum_distance_combo_box, 1, 1, 1, 1)
        self.output_frame_size_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_frame_size_label.setFont(font)
        self.output_frame_size_label.setObjectName("output_frame_size_label")
        self.gridLayout.addWidget(self.output_frame_size_label, 4, 0, 1, 1)
        self.input_video_file_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_video_file_label.setFont(font)
        self.input_video_file_label.setObjectName("input_video_file_label")
        self.gridLayout.addWidget(self.input_video_file_label, 0, 0, 1, 1)
        self.proceed_to_detection_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proceed_to_detection_button.sizePolicy().hasHeightForWidth())
        self.proceed_to_detection_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.proceed_to_detection_button.setFont(font)
        self.proceed_to_detection_button.setObjectName("proceed_to_detection_button")
        self.gridLayout.addWidget(self.proceed_to_detection_button, 6, 1, 1, 1)
        self.minimum_distance_input_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minimum_distance_input_label.setFont(font)
        self.minimum_distance_input_label.setObjectName("minimum_distance_input_label")
        self.gridLayout.addWidget(self.minimum_distance_input_label, 1, 0, 1, 1)
        self.time_to_wait_in_between = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_to_wait_in_between.sizePolicy().hasHeightForWidth())
        self.time_to_wait_in_between.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_to_wait_in_between.setFont(font)
        self.time_to_wait_in_between.setObjectName("time_to_wait_in_between")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.time_to_wait_in_between.addItem("")
        self.gridLayout.addWidget(self.time_to_wait_in_between, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_webcam_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_webcam_button.sizePolicy().hasHeightForWidth())
        self.select_webcam_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.select_webcam_button.setFont(font)
        self.select_webcam_button.setObjectName("select_webcam_button")
        self.horizontalLayout.addWidget(self.select_webcam_button)
        self.online_video_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.online_video_button.sizePolicy().hasHeightForWidth())
        self.online_video_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.online_video_button.setFont(font)
        self.online_video_button.setObjectName("online_video_button")
        self.horizontalLayout.addWidget(self.online_video_button)
        self.browse_video_file_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_video_file_button.sizePolicy().hasHeightForWidth())
        self.browse_video_file_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browse_video_file_button.setFont(font)
        self.browse_video_file_button.setObjectName("browse_video_file_button")
        self.horizontalLayout.addWidget(self.browse_video_file_button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.time_to_wait_in_between_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_to_wait_in_between_label.setFont(font)
        self.time_to_wait_in_between_label.setObjectName("time_to_wait_in_between_label")
        self.gridLayout.addWidget(self.time_to_wait_in_between_label, 3, 0, 1, 1)
        self.time_to_wait_to_start_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_to_wait_to_start_label.setFont(font)
        self.time_to_wait_to_start_label.setObjectName("time_to_wait_to_start_label")
        self.gridLayout.addWidget(self.time_to_wait_to_start_label, 2, 0, 1, 1)
        self.alert_filname_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alert_filname_label.setFont(font)
        self.alert_filname_label.setObjectName("alert_filname_label")
        self.gridLayout.addWidget(self.alert_filname_label, 5, 0, 1, 1)
        self.frame_size_combobox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_size_combobox.sizePolicy().hasHeightForWidth())
        self.frame_size_combobox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_size_combobox.setFont(font)
        self.frame_size_combobox.setObjectName("frame_size_combobox")
        self.frame_size_combobox.addItem("")
        self.frame_size_combobox.addItem("")
        self.frame_size_combobox.addItem("")
        self.gridLayout.addWidget(self.frame_size_combobox, 4, 1, 1, 1)
        self.alert_file_browser_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alert_file_browser_button.sizePolicy().hasHeightForWidth())
        self.alert_file_browser_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alert_file_browser_button.setFont(font)
        self.alert_file_browser_button.setObjectName("alert_file_browser_button")
        self.gridLayout.addWidget(self.alert_file_browser_button, 5, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.time_to_wait_to_start_combo_box.setCurrentIndex(5)
        self.minimum_distance_combo_box.setCurrentIndex(3)
        self.frame_size_combobox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_to_wait_to_start_combo_box.setItemText(0, _translate("MainWindow", "5 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(1, _translate("MainWindow", "10 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(2, _translate("MainWindow", "15 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(3, _translate("MainWindow", "20 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(4, _translate("MainWindow", "25 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(5, _translate("MainWindow", "30 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(6, _translate("MainWindow", "35 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(7, _translate("MainWindow", "40 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(8, _translate("MainWindow", "45 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(9, _translate("MainWindow", "50 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(10, _translate("MainWindow", "55 Seconds"))
        self.time_to_wait_to_start_combo_box.setItemText(11, _translate("MainWindow", "60 Seconds"))
        self.minimum_distance_combo_box.setItemText(0, _translate("MainWindow", "0.5 Meters"))
        self.minimum_distance_combo_box.setItemText(1, _translate("MainWindow", "1 Meters"))
        self.minimum_distance_combo_box.setItemText(2, _translate("MainWindow", "1.5 Meters"))
        self.minimum_distance_combo_box.setItemText(3, _translate("MainWindow", "2 Meters"))
        self.minimum_distance_combo_box.setItemText(4, _translate("MainWindow", "2.5 Meters"))
        self.minimum_distance_combo_box.setItemText(5, _translate("MainWindow", "3 Meters"))
        self.output_frame_size_label.setText(_translate("MainWindow", "Output Video Frame Size"))
        self.input_video_file_label.setText(_translate("MainWindow", "Input video file:"))
        self.proceed_to_detection_button.setText(_translate("MainWindow", "Proceed"))
        self.minimum_distance_input_label.setText(_translate("MainWindow", "Minimum distance to maintain between people:"))
        self.time_to_wait_in_between.setItemText(0, _translate("MainWindow", "5 Seconds"))
        self.time_to_wait_in_between.setItemText(1, _translate("MainWindow", "10 Seconds"))
        self.time_to_wait_in_between.setItemText(2, _translate("MainWindow", "15 Seconds"))
        self.time_to_wait_in_between.setItemText(3, _translate("MainWindow", "20 Seconds"))
        self.time_to_wait_in_between.setItemText(4, _translate("MainWindow", "25 Seconds"))
        self.time_to_wait_in_between.setItemText(5, _translate("MainWindow", "30 Seconds"))
        self.time_to_wait_in_between.setItemText(6, _translate("MainWindow", "35 Seconds"))
        self.time_to_wait_in_between.setItemText(7, _translate("MainWindow", "40 Seconds"))
        self.time_to_wait_in_between.setItemText(8, _translate("MainWindow", "45 Seconds"))
        self.time_to_wait_in_between.setItemText(9, _translate("MainWindow", "50 Seconds"))
        self.time_to_wait_in_between.setItemText(10, _translate("MainWindow", "55 Seconds"))
        self.time_to_wait_in_between.setItemText(11, _translate("MainWindow", "60 Seconds"))
        self.select_webcam_button.setText(_translate("MainWindow", "WebCam"))
        self.online_video_button.setText(_translate("MainWindow", "Online Video"))
        self.browse_video_file_button.setText(_translate("MainWindow", "Browse"))
        self.time_to_wait_in_between_label.setText(_translate("MainWindow", "Time to wait between playing warnings:"))
        self.time_to_wait_to_start_label.setText(_translate("MainWindow", "Time to wait before playing warning:"))
        self.alert_filname_label.setText(_translate("MainWindow", "Input alert mp3 file:"))
        self.frame_size_combobox.setItemText(0, _translate("MainWindow", "720 x 480"))
        self.frame_size_combobox.setItemText(1, _translate("MainWindow", "1280 x 720"))
        self.frame_size_combobox.setItemText(2, _translate("MainWindow", "1920 x 1080"))
        self.alert_file_browser_button.setText(_translate("MainWindow", "Browse mp3 file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

